spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# fastDFS 配置
fdfs:
  # 连接超时
  connect-timeout: 60
  # 读取时间
  so-timeout: 15000
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - test.ip:22122
